postgres:
  port: '5432'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
influxdb:
  port: '8086'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
communication:
  devicePins:
    heater: 0
    circulation: 1
  arduinoCommands:
    -
      - sensorValue
      - ss
    -
      - commandReceived
      - ""
    -
      - toggleDevice
      - i?
    -
      - poll
      - ""
    -
      - error
      - s
sensorList:
  - "water_temp"
  - "lux"
  - "pH"
  - "humidity"
  - "air_temp"
  - "co2"