postgres:
  port: '5432'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
influxdb:
  port: '8086'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
communication:
  arduinoDevice: "/dev/tty.usbmodem1411"
  arduinoCommands:
    -
      - sensorValue
      - ss
    -
      - commandReceived
      - ss
    -
      - toggleDevice
      - ss
sensorList:
  - "waterTemp"
  - "lux"
  - "pH"
  - "humidity"
  - "airTemp"
  - "co2"