restEndpoint:
  port: 8001
  host: '0.0.0.0'
postgres:
  port: '5432'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
influxdb:
  port: '8086'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
communication:
  devicePins:
    air_cooler: 1
    water_heater: 2
    water_cooler: 3
    ph_up: 4
    ph_down: 5
    water_soil: 6
    increase_c02: 8
    dehumidifier: 11
    co2_up: 12
    co2_down: 13
    external_air: 24
    circulation_fan: 22
    lights: 24
    humidifier: 26
    air_heater: 28

  arduinoCommands:
    -
      - sensorValue
      - ss
    -
      - commandReceived
      - s
    -
      - toggleDevice
      - i?
    -
      - poll
      - ""
    -
      - error
      - s
sensorList:
  - "water_temp"
  - "lux"
  - "pH"
  - "humidity"
  - "air_temp"
  - "co2"