postgres:
  port: '5432'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
influxdb:
  port: '8086'
  db: 'greenhouse'
  username: 'greenhouse'
  password: 'greenhouse'
  host: 'localhost'
communication:
  arduinoCommands:
    -
      - sensorValue
      - ss
    -
      - commandReceived
      - ss
    -
      - toggleDevice
      - ss
sensorList:
  - "water_temp"
  - "lux"
  - "pH"
  - "humidity"
  - "air_temp"
  - "co2"